// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prison-hud/Current.tsx": () => import("../components/mockups/prison-hud/Current.tsx"),
  "./components/mockups/prison-sidebar/CommandDeck.tsx": () => import("../components/mockups/prison-sidebar/CommandDeck.tsx"),
  "./components/mockups/prison-sidebar/CompactRail.tsx": () => import("../components/mockups/prison-sidebar/CompactRail.tsx"),
  "./components/mockups/prison-life-shell/Industrial.tsx": () => import("../components/mockups/prison-life-shell/Industrial.tsx")
};
